### ISSUE TITLE
Dandelion Orgs 🌼

### ISSUE THREAD

**Issue by burrrata** [aragon/security-review#12]
1Hive is developing a set of Aragon apps that will allow anyone to recreate the functionality of MolochDAO on Aragon. This will highlight the power of the Aragon platform to quickly and securely deploy a DAO. It will also showcase the modular composible nature of Aragon as a platform where any DAO can easily integrate the Dandelion suite of apps into their DAO, or extend the Dandelion model with additional Aragon apps.

We are a small, but passionate team that has been working around the clock even before our grant was awarded. We're very excited about this project, but also have a very tight budget. Recently MolochDAO has been managing over 1mm in ETH. If people are going to use Aragon for similar use cases, the Dandelion apps need to be bullet proof. 

We're about half way thorugh the development process, but would like to start the conversation now as to what the possibilities are for security audits, what resources are available to Aragon teams, and what we can do to make it as easy as possible for our apps to be audited. I've taken the lead on this endeavor and created a consistent development process that we are using for all of our apps based on best practices and recommendations by Trail of Bits, Consensys Dilligence, and ETHSecurity. We are releasing all of our apps with full documentation, user guides, and infographics explaining what each app does, why, and how to install and use them. In addition we will perform our own internal review and release a paper detailing recommended configurations, open questions, and potential attack vectors.

All of this will make it easy for anyone to learn about and use our apps, however the target audience is a security team. We do not have the resources within our budget to carry out a security audit on our own, but we want to make it as easy as possible for whoever does. With that in mind, starting a conversation here to see if the AA would be open to sponsoring a security audit of the Dandelion Org Aragon apps.

**Comment by burrrata** [comment]
Following up because we're about half way through development (maybe even more) and need to start engaging security partners. After contacting several potential security partners the general consensus is that they prefer 8-12 weeks lead time, but some might be able to work with 6-8. In order to not stall and postpone shipment, I'd like to line this up sooner than later. Is the AA able to advise and/or support our efforts to ensure that MolochDAO on Aragon is secure?

**Comment by sohkai** [comment]
Completed by Consensys Diligence.
