### ISSUE TITLE
Payroll Aragon app

### ISSUE THREAD

**Issue by sohkai** [aragon/security-review#4]
# Payroll app

**Description**: Employee payroll, by the block, in any token.

Notes:

- Delegates price information for tokens to an external `IFeed` contract
  - Price feed can be implemented either through a user-controlled server ("Passive Price Feed", see below), or as an on-chain mirror of an oracle like [DAI's](https://github.com/aragon/ppf/issues/15)
- Includes functionality for adding reimbursements and employee bonuses
- Interacts with an installed Finance app (and therefore a Vault app as well) to create recurring salary accounts that employees can withdraw from

**Contracts**:

- [Payroll](https://github.com/aragon/aragon-apps/blob/master/future-apps/payroll/contracts/Payroll.sol)
- [Passive Price Feed](https://github.com/aragon/ppf/tree/master/packages/ppf-contracts)

**Status**: Ready to review, will include a more complete spec and threat model assumption before audit starts.

**Comment by maurelian** [comment]
@sohkai do you feel the need for a formal report, with the whole initial and mitigations phase? 
Or would handling this a bit more like the whole late/great 'ongoing support' thing work, in which we review for a week, then submit issues in the repo?

**Comment by sohkai** [comment]
@maurelian I mentioned this privately, but for the sake of the AA it would likely help to have a breakdown of the differences in cost between the two.

In this case, because Payroll will handle direct funds and is what I'd consider to be a fairly sensitive contract for both the organization and its employees, I'd favour a more formal approach cc @LouisGrx

**Comment by sohkai** [comment]
Closing as audit has been completed.
