### ISSUE TITLE
Aragon Network: Court

### ISSUE THREAD

**Issue by sohkai** [aragon/security-review#7]
# Aragon Network: Court

**Description**: A decentralized "court" that can arbitrate "human-readable", subjective disputes. Juries are randomly selected from staked participants to vote in the arbitration process (through partial-commit-reveal) and incentivized with various token models (fees, redistribution based on correctness).

**Repo**: https://github.com/aragon/aragon-court

**Scope**: production smart contracts in the repo (`contracts/**/*`, except for `contracts/test/**/*`)

**Spec**: soon™️

**Status**: Will be ready for auditing in early October

**Comment by maurelian** [comment]
To what extent should we expect the Court and Staking to be similar? 

I see that Court.sol inherits an erc900.sol interface, but reimplement the functions quite differently from Staking.sol.

**Comment by bingen** [comment]
@maurelian There's no a final decision on this yet. Actually I already have a local branch with Staking split from Court. The Staking code contained in Court contract should be quite similar, but with less functionality.
A littel bit more of context here: https://github.com/aragon/aragon-court/pull/6#discussion_r261555713

**Comment by sohkai** [comment]
Done separately.
